### PR TITLE
Possible fix for performance drop on M1 Mac

### LINKED ISSUE #99: Performance drop on M1 Mac
- Operating system: M1 mac
- Python version: Python 3.8
- pyvirtualcam version: Latest
- Virtual camera (OBS, v4l2loopback, UnityCapture): OBS
- Virtual camera version: Latest

**Describe the bug**
Noticeable performance drop when using pyvirtualcam on M1 mac versus Intel mac. Output stream is laggy and has low FPS. Didn't change any of the source code so not sure where I am going wrong.

### PR DESCRIPTION
**Pull request by letmaik**
Fixes #99.

### CODE REVIEW

**Comment by letmaik** [comment]
@avinashsureka @IDDD-Dennis @janmonterrubio Could you download the wheels from https://github.com/letmaik/pyvirtualcam/suites/8987765308/artifacts/413747758 and test whether this fixes the performance issue you were seeing with M1 Macs?

**Comment by janmonterrubio** [comment]
> so what I meant to say was, can you build this branch locally and test?

Yep, I believe all your recent changes are on obs 28.x , so I will make that upgrade today too. Thank you so much for keeping up with this.

**Comment by janmonterrubio** [comment]
## M1 / Slack / Pyvirtualcam

obs28_slack

## M1 / Teams / PyVirtualcam

obs28_teams


I think this fixes it @letmaik , thank you SO SO SO much for digging through this.

**Comment by letmaik** [comment]
@janmonterrubio Awesome, thanks for testing!

**Pull request merged**
